name: TutorialPlugin
main: my.test.plugin.tutorialplugin.Main
version: 0.0.1
author: Itsu
api: ["1.0.0"]

commands:
   show:
      description: "プレイヤーの情報確認"
      usage: "/show <player>"
      permission: tutorialplugin.ip
      permission-message: You don't have <permission>
      default: op