name: PlayerInfo
main: player.info.playerinfo.Main
version: 1.0.0
author: Itsu
api: ["1.0.0"]

commands:
   show:
      description: "プレイヤーの情報確認"
      usage: "/show <player>"
      permission: tutorialplugin.ip
      permission-message: You don't have <permission>
      default: op