name: BackAndForth
main: com.Itsu.Main
version: 1.0.0
author: Itsu
api: ["1.0.0"]

commands:
   baf:
      description: "サーバー移動"
      usage: "/baf <ip>, <ポート>"
      permission: baf.com
      permission-message: You don't have permisson
      default: true
   baf.com:
      default: true